export const Footer = () => {
  return (
    <>
      <footer className=" bg-gradient-to-b from-slate-800 to-black text-slate-500 text-center p-4">
        <p>© 2024 Linyi Huang</p>
        <p>Images generated by DALLE</p>
      </footer>
    </>
  );
};
